---
- hosts: localhost
  vars:
    master: https://192.168.42.53:8443
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJhbnNpYmxlIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InN1cGVyc2EtdG9rZW4tZGtqbmsiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoic3VwZXJzYSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImZhMzU1NzkxLWZkNWYtMTFlOC1iZmM2LTUyNTQwMDAwZGRlNCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDphbnNpYmxlOnN1cGVyc2EifQ.Y1XSfYYUhMdA_H6CT0A-7BWtsuD6VOxwDvmXn_dhD7FMWc-lA5WfG1JfwGxGM9ISFcgJOWyYLeDz8ebICtT0WA4A7VeQxARc_7RmWttQKCedKhtFYS3qXpR_Xs4NzDhy3Totqvazx-1mrTGpozEKdgWPnE8hYt_T6JJl_UlcTPoQVjPem4cEneESnGps8kuD92LVrYowu2pecrep94iYNEIbcmBEetYYEllHGBMUNGi-i1TgASt2taCHGKKrjHU410LKbWgCV0Hb5GQDuP_Pg2w_5nQbQrwG7i0BZYWKxQunUTdZxJZUIc1IMsGGjxm1P1D1ROh-tjVGWvqeh6uNrg
  tasks:
  - name: Make sure OpenShift python module is present
    pip:
      name: openshift
      executable: pip3

  - name: Delete all PVC
    k8s:
      api_version: v1
      kind: PersistentVolumeClaim
      state: absent
      namespace: ansible
      name: claim1
      host: "{{ master }}"
      api_key: "{{ token }}"
      verify_ssl: no
